name: talimger_mobile
description: A new Flutter project.
publish_to: "none"

version: 1.0.1+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  url_launcher: ^6.2.5
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  shared_preferences: ^2.2.2
  fluttertoast: ^8.2.4
  firebase_messaging: ^14.7.20
  flutter_rating_bar: ^4.0.1
  pod_player: ^0.2.1
  flutter_pdfview: ^1.3.2
  device_info_plus: ^10.1.0
  package_info_plus: ^7.0.0
  crypto: ^3.0.3
  flutter_widget_from_html_core: ^0.14.11
  translator: ^1.0.0
  easy_localization: ^3.0.5
  hive_flutter: ^1.1.0
  salomon_bottom_bar: ^3.3.2
  flutter_riverpod: ^2.5.1
  file_picker: ^8.0.1
  carousel_slider: ^4.2.1
  google_fonts: ^6.2.1
  line_icons: ^2.0.3
  feather_icons: ^1.2.0
  cached_network_image: ^3.3.1
  simple_animations: ^5.0.2
  font_awesome_flutter: ^10.7.0
  flutter_web_browser: ^0.17.1
  quiver: ^3.2.1
  permission_handler: ^11.3.1
  flutter_svg: ^2.0.10+1
  image_picker: ^1.0.7
  firebase_storage: ^11.6.10
  material_dialogs: ^1.1.4
  path_provider: ^2.1.2
  app_settings: ^5.1.1
  loading_indicator: ^3.1.1
  smooth_page_indicator: ^1.1.0
  launch_review: ^3.0.1
  shimmer: ^3.0.0
  html_unescape: ^2.0.0
  share_plus: ^8.0.2
  screen_protector: ^1.4.2
  rounded_loading_button:
    git:
      url: https://github.com/scopendo/flutter_rounded_loading_button.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  image_path_ios: "assets/images/logo.jpg"
  image_path: "assets/images/logo.jpg"
  remove_alpha_ios: true
  min_sdk_android: 21

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/animations/
    - assets/images/
    - assets/translations/
